spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://192.168.31.9:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.31.9
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 192.168.31.9
    database: 0
    port: 6379
    password: 123456
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
#    host: http://192.168.91.128/
    host: http://192.168.31.9/